// apps/vue-mfe/src/App.vue
<script setup>
import { container as headerContainer } from "styles/header.css";
import { grid } from "./App.css";

import Card from "./components/Card.vue";
</script>

<template>
  <div>
    <!-- :class is used to reference the classNamesas local variables, instead of using {} -->
    <div :class="headerContainer">
      <img
        src="./assets/vue.svg"
        alt="Vue logo"
        style="width: 25px; height: 25px"
      />
      <div>Vue on Vite</div>
    </div>
    <div :class="grid">
      <Card
        imageSrc="ghost.jpeg"
        imageAlt="Ghost of Tsushima"
        title="Ghost of Tsushima"
        description="Uncover the hidden wonders of Tsushima in this open-world action adventure from Sucker Punch Productions and PlayStation Studios."
      />
      <Card
        imageSrc="gog.jpeg"
        imageAlt="Marvel's Guardians of the Galaxy"
        title="Marvel's Guardians of the Galaxy"
        description="Marvel's Guardians of the Galaxy is a 2021 action-adventure game developed by Eidos-Montréal and published by Square Enix."
      />
    </div>
  </div>
</template>

// apps/qwik-version/src/app.jsx
import { component$, useSignal } from '@builder.io/qwik';
 
import { container as headerContainer} from "styles/header.css";
import { button } from "styles/button.css";
import qwikLogo from './assets/qwik.svg';
import { grid } from './app.css';
import {
  container,
  image,
  content,
  actions,
  title as titleStyle,
  description as descriptionStyle,
} from 'styles/card.css'


// component$ is used to define a component in Qwik
const Button = component$(({ children, ...props }) => (
  <button class={button} {...props}>
    <Slot />
  </button>
));

const Card = component$(({ imageSrc, imageAlt, title, description }) => (
  <div class={container}>
    <img src={imageSrc} alt={imageAlt} class={image} />
    <div class={content}>
      <div class={titleStyle}>{title}</div>
      <div class={descriptionStyle}>{description}</div>
      <div class={actions}>
        <Button>Order This Mouse Now!</Button>
      </div>
    </div>
  </div>
));

export const App = component$(() => { 

  return (
    <>
      <div className={headerContainer}>
        <img 
          src={qwikLogo} 
          alt="Qwik Logo"
          style="width: 25px; height:25px;"
        />
        <div className="">This Card was made using Qwik</div>
      </div>
      <div class={grid}>
        <Card
          imageSrc="./returnal.jpeg"
          imageAlt="Returnal"
          title="Returnal"
          description="Returnal is a 2021 roguelike video game developed by Housemarque and published by Sony Interactive Entertainment.."
        />
        <Card
          imageSrc="./nfs.jpeg"
          imageAlt="Need for Speed Unbound"
          title="Need for Speed Unbound"
          description="Need for Speed Unbound is a 2022 racing video game, the twenty-fifth instalment in the Need for Speed series."
        />
      </div>
    </>
  )
})
