// apps/web/app/page.tsx
import Image from "next/image";
import { grid } from "./page.css";
import { button } from  "styles/button.css"
import { container, 
  image, 
  content, 
  actions, 
  title as titleStyle, 
  description as descriptionStyle 
} from  "styles/card.css"

const Button = ({ children, ...props }) =>(
  <button className={button} {...props}>
    {children}
  </button>
);

const Card = ({ imageSrc, imageAlt, title, description }) => (
  <div className={container}>
    <Image
      src={imageSrc}
      alt={imageAlt}
      width={1024}
      height={1024}
      className={image}
    />
    <div className={content}>
      <div className={titleStyle}>{title}</div>
      <div className={descriptionStyle}>{description}</div>
      <div className={actions}>
        <Button>Order This Mouse Now!</Button>
      </div>
    </div>
  </div>
)

export default function Page(): JSX.Element {
  return (
    <>
      <div className={grid}>
        <Card
          imageSrc="/horizon.jpeg"
          imageAlt="Horizon Forbidden West"
          title="Horizon Forbidden West"
          description="Horizon Forbidden West is a 2022 action role-playing game developed by Guerrilla Games and published by Sony Interactive Entertainment. "
        />
        <Card
          imageSrc="/immortals.jpeg"
          imageAlt="Immortals of Aveum"
          title="Immortals of Aveum"
          description="Immortals of Aveum is a first-person shooter game developed by Ascendant Studios and published by Electronic Arts."
        />
      </div>
    </>
  );
}

// apps/qwik-version/src/app.jsx
import { component$, useSignal } from '@builder.io/qwik';
 
import { container as headerContainer} from "styles/header.css";
import { button } from "styles/button.css";
import qwikLogo from './assets/qwik.svg';
import { grid } from './app.css';
import {
  container,
  image,
  content,
  actions,
  title as titleStyle,
  description as descriptionStyle,
} from 'styles/card.css'


// component$ is used to define a component in Qwik
const Button = component$(({ children, ...props }) => (
  <button class={button} {...props}>
    <Slot />
  </button>
));

const Card = component$(({ imageSrc, imageAlt, title, description }) => (
  <div class={container}>
    <img src={imageSrc} alt={imageAlt} class={image} />
    <div class={content}>
      <div class={titleStyle}>{title}</div>
      <div class={descriptionStyle}>{description}</div>
      <div class={actions}>
        <Button>Order This Mouse Now!</Button>
      </div>
    </div>
  </div>
));

export const App = component$(() => { 

  return (
    <>
      <div className={headerContainer}>
        <img 
          src={qwikLogo} 
          alt="Qwik Logo"
          style="width: 25px; height:25px;"
        />
        <div className="">This Card was made using Qwik</div>
      </div>
      <div class={grid}>
        <Card
          imageSrc="./returnal.jpeg"
          imageAlt="Returnal"
          title="Returnal"
          description="Returnal is a 2021 roguelike video game developed by Housemarque and published by Sony Interactive Entertainment.."
        />
        <Card
          imageSrc="./nfs.jpeg"
          imageAlt="Need for Speed Unbound"
          title="Need for Speed Unbound"
          description="Need for Speed Unbound is a 2022 racing video game, the twenty-fifth instalment in the Need for Speed series."
        />
      </div>
    </>
  )
})
